"""Scoped SSH helper. Credentials are read in memory, never persisted or printed.

Examples: python scripts/remote.py inspect --host 151 --credentials-pdf fangc-README.pdf
The optional --command is an explicit operator command, not generated by an agent.
"""
import argparse
import contextlib
import json
import logging
import os
import re
import shlex
import socketserver
import threading
import select
from pathlib import Path
import paramiko

HOSTS={"151":"10.103.11.151","158":"10.103.10.158"}


def credentials(pdf=None):
    user=os.getenv("LAB_SSH_USER","fangc")
    password=os.getenv("LAB_SSH_PASSWORD")
    if pdf and not password:
        from pypdf import PdfReader
        text="\n".join(p.extract_text() for p in PdfReader(pdf).pages)
        user=re.search(r"用户名\s*[:：]\s*(\S+)",text).group(1)
        password=re.search(r"初始密码\s*[:：]\s*(\S+)",text).group(1)
    return user,password


@contextlib.contextmanager
def connection(host,pdf=None):
    user,password=credentials(pdf)
    clients=[]
    def connect(address,sock=None):
        client=paramiko.SSHClient();client.load_system_host_keys()
        # Persist trust-on-first-use pins in the project's ignored runtime directory.
        known=Path("runs/ssh_known_hosts");known.parent.mkdir(parents=True,exist_ok=True)
        if known.exists():client.load_host_keys(str(known))
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        client.connect(address,username=user,password=password,sock=sock,timeout=20,auth_timeout=20)
        client.save_host_keys(str(known));clients.append(client);return client
    try:
        sock=None
        if host=="158":
            jump=connect("10.103.10.157")
            sock=jump.get_transport().open_channel("direct-tcpip",(HOSTS[host],22),("127.0.0.1",0))
        yield connect(HOSTS[host],sock)
    finally:
        for client in reversed(clients):client.close()


def command(client,text,timeout=60):
    _,stdout,stderr=client.exec_command(text,timeout=timeout)
    output=stdout.read().decode(errors="replace")
    errors=stderr.read().decode(errors="replace")
    return {"exit_code":stdout.channel.recv_exit_status(),"stdout":output,"stderr":errors}


def tunnel(client,local_port,remote_port):
    class Handler(socketserver.BaseRequestHandler):
        def handle(self):
            channel=client.get_transport().open_channel("direct-tcpip",("127.0.0.1",remote_port),self.request.getpeername())
            try:
                while True:
                    ready,_,_=select.select([self.request,channel],[],[],30)
                    for source in ready:
                        data=source.recv(65536)
                        if not data:return
                        (channel if source is self.request else self.request).sendall(data)
            finally:channel.close()
    class Server(socketserver.ThreadingTCPServer):
        allow_reuse_address=True
        daemon_threads=True
    return Server(("127.0.0.1",local_port),Handler)


def main():
    parser=argparse.ArgumentParser();parser.add_argument("action",choices=["inspect","exec","tunnel","upload"])
    parser.add_argument("--host",choices=HOSTS,default="151");parser.add_argument("--credentials-pdf")
    parser.add_argument("--command");parser.add_argument("--local-port",type=int,default=18151);parser.add_argument("--remote-port",type=int,default=18151)
    parser.add_argument("--local");parser.add_argument("--remote")
    args=parser.parse_args()
    logging.getLogger("paramiko").setLevel(logging.CRITICAL)
    with connection(args.host,args.credentials_pdf) as client:
        if args.action=="inspect":
            py="/data/fangc/envs/vllm-0.8.5/bin/python" if args.host=="151" else "/data/fangc/envs/sglang-qwen38-260915/bin/python"
            cmd=f"hostname; PYTHONPATH=/data/fangc/teamlearn/gpu_tools {py} -m gpustat --no-color; {py} -c 'import sys; print(sys.version)'"
            print(json.dumps(command(client,cmd),ensure_ascii=False,indent=2))
        elif args.action=="exec":
            if not args.command:parser.error("--command required")
            print(json.dumps(command(client,args.command),ensure_ascii=False,indent=2))
        elif args.action=="upload":
            if not args.local or not args.remote:parser.error("--local and --remote required")
            if not args.remote.startswith(("/home/fangc/teamlearn/","/data/fangc/teamlearn/")):parser.error("upload destination must be in project-specific remote directory")
            command(client,"mkdir -p "+shlex.quote(str(Path(args.remote).parent).replace("\\","/")))
            with client.open_sftp() as sftp:sftp.put(args.local,args.remote)
            print("uploaded",args.remote)
        else:
            server=tunnel(client,args.local_port,args.remote_port)
            print(f"SSH tunnel ready on 127.0.0.1:{args.local_port}",flush=True)
            try:server.serve_forever()
            finally:server.server_close()


if __name__=="__main__":main()
